### ISSUE TITLE
Bug? Global variables with type = time

### ISSUE THREAD

**Issue by gustvao** [ady624/webCoRE#20]
I have a simple piston that turns on my lights if certain conditions are met + **TIME** is between 2 global variables (variables type = time). Piston code -> 49neg

![image](https://user-images.githubusercontent.com/5428331/27997751-8459e654-64d5-11e7-98ec-31f1d073dc6b.png)

The thing is, when the piston checks the is between condition, it returns false because 1 of the global variables has the year 1970...

``Comparison 66708334 is_between 1970-01-01T16:00:00.000Z .. 2017-07-10T01:00:00.000Z = false (14ms)``

Those are the values, in local time of my global variables used with this piston:

![image](https://user-images.githubusercontent.com/5428331/27997749-7742c8dc-64d5-11e7-8c2b-e8447ebdb976.png)

Any ideas of why the global variable gets set with the year 1970 and how to fix this?

Tks vm and congrats for the project, it is amazing!!

**Comment by gustvao** [comment]
more info...

I found out that if I setup the global variable by time, it defaults to 1970 (which is start of unix time counter)... so obviously I tried starting with DATETIME and then switched only to type TIME before clicking save and it worked..

so in logs the comparison was considering the correct datetimes but was still defaulting to false...

So i went to conver the unix time of the example to current date and, to my surprise:

![image](https://user-images.githubusercontent.com/5428331/28049067-2b2d5e3e-65cb-11e7-9897-a0b14e477787.png)


So when using time comparison, for some reason you guys create the date with some reference of unix time where the TIME should get the reference from now, as I believe.

Can you pls help me fix this? Should be a simple fix..

Tks and let me know if I can help
Gustavo

**Comment by ady624** [comment]
Problem was with variables set via the UI - there is no casting performed on them at set time (pistons cast them into their proper type while saving them, the UI does not) - enforcing casting on read fixed the problem, will look for a way to cast them at write time - casting is a function of the piston code, setting global variables does not involve any piston, therefore the cast function is not easily available at that time.

Fixed in v0.2.0d3

**Comment by gustvao** [comment]
@ady624 still not working..

now both globals are set to unix time on comparison but all them (globals and current TIME) are defaulting to 1970ish..

still not working as it should

```Comparison 86257759 is_not_between 9000000 .. 36000000 = true (10ms)```

![image](https://user-images.githubusercontent.com/5428331/28099842-34fe9598-6695-11e7-8573-89bee6715e2c.png)
![image](https://user-images.githubusercontent.com/5428331/28099866-4cf5af4c-6695-11e7-9d1c-a657b004ca70.png)
![image](https://user-images.githubusercontent.com/5428331/28099877-5c775880-6695-11e7-93fd-cbcee01feeab.png)

**Comment by gustvao** [comment]
more info:

now my time global variables get changed to a fixed value all the time the piston run.. 

![image](https://user-images.githubusercontent.com/5428331/28100202-171f2b9e-6697-11e7-8f47-48950ae5c948.png)


![image](https://user-images.githubusercontent.com/5428331/28100226-314fb4ac-6697-11e7-8a55-ef396c2789d3.png)

**Comment by ady624** [comment]
the time variable is a timestamp modded to 86400000 max. 9000000 means 2:30am, 36000000 means 10am, and 86257759 is about 11:57pm

**Comment by gustvao** [comment]
@ady624 I dont understand how you convert 36000000 to 10am UTC, I am using time conversor like this https://www.epochconverter.com/ and they all return 4pm.

The thing is, even if your conversion being correct, the dates of those timestamps are in different years, so the comparison by time wont work because they are not in the "same era".

Also, TIME was not 

Anyways, I see 2 issues still:

1) the comparison is still returning the wrong result for in between... from what you mention, 11h57 was my current time, but you said it was in UTC. Maybe TIME variable is not considering timezone?

2) after you made the last commit, my global variables get RESET to random values after the piston run. This is super odd.

So I set them up as:

![image](https://user-images.githubusercontent.com/5428331/28167336-a7f60c94-67b1-11e7-83b5-872f527913e6.png)

and after the piston runs it changes the global variables (despite I never instructed the piston to do so) to:

![image](https://user-images.githubusercontent.com/5428331/28167300-81efc1b6-67b1-11e7-9767-cad654a56ce3.png)

Any ideas?

**Comment by gustvao** [comment]
for issue number 2 I understood what is going on, you are converting my BRT global variables to UTC global variables..

**Comment by gustvao** [comment]
@ady624 I understood what is going on, here is the explanation (I still think a fix must be done)

So your comparison is working fine, the issue is that the PISTON changes the value of the TIME GLOBAL VARIABLE after it is run for the first time, I guess?

And it converts the TIME GLOBAL variable that I put in my current BRT timezone to UTC, therefore, causing unexpected behaviours.

So what I had to do to make it work properly was:

If I needed 10AM BRT, for exemple, I had to put in TIME GLOBAL VARIABLE 7AM, because 7AM BRT means 10AM UTC and when the comparison is made, the SYSTEM TIME VARIABLE is in UTC but actually reflects atual BRT time. So if now is 10AM BRT, SYSTEM TIME VARIABLE in comparison is 10AM UTC...

It is a bit confusing, let me know if you have any questions.

My suggestion is to make it somehow you SELECT the TIMEZONE when you create the GLOBAL VARIABLE or always assume it is your LOCAL TIMEZONE.

Let me know if you need any other info.

**Comment by gustvao** [comment]
@ady624 should you reopen this one?

**Comment by ady624** [comment]
I need to look into this closer. Got any steps to reproduce the issue?
